
export function buildAppDevAwsPostgresTemplate() {
    const content = `# Application Development Plan: AWS & PostgreSQL

## 1. Executive Summary
Development of a scalable web application hosted on AWS, utilizing PostgreSQL for persistent data storage and secure user authentication.

## 2. System Architecture
This diagram outlines the high-level architecture:
- **Frontend**: Hosted on S3 distributed via CloudFront.
- **Backend**: API Gateway triggering Lambda functions (or EC2) for business logic.
- **Database**: Amazon RDS for PostgreSQL.
- **Auth**: AWS Cognito for user management and authentication.
- **Settings**: Stored in PostgreSQL linked to User ID.

\`\`\`mermaid
graph TD
    User((User))
    
    subgraph AWS_Cloud ["AWS Cloud Environment"]
        style AWS_Cloud fill:#f9f9f9,stroke:#333,stroke-dasharray:5,5
        
        subgraph Frontend_Hosting ["Frontend Hosting"]
            style Frontend_Hosting fill:#e6fffa,stroke:#3bb
            CF["CloudFront CDN"]
            S3["S3 Bucket - Static Assets"]
        end
        
        subgraph Backend_Services ["Backend Services"]
            style Backend_Services fill:#fff5f5,stroke:#f56565
            API["API Gateway"]
            Compute["Lambda / EC2 Server"]
            Cognito["AWS Cognito <br/>(Auth & User Directory)"]
        end
        
        subgraph Data_Persistence ["Data Persistence"]
            style Data_Persistence fill:#ebf8ff,stroke:#4299e1
            RDS[("Amazon RDS <br/> PostgreSQL")]
            Secrets["Secrets Manager <br/>(DB Credentials)"]
        end
    end

    %% Flows
    User -->|"1. Access Web App"| CF
    CF -->|"Retrieve Content"| S3
    
    User -->|"2. Authenticate"| Cognito
    Cognito -->|Token| User
    
    User -->|"3. API Requests (with Token)"| API
    API -->|"Route Request"| Compute
    
    Compute -->|"Validate Token"| Cognito
    Compute -->|"Read Creds"| Secrets
    Compute -->|"Query/Transaction"| RDS
    
    %% User Settings Logic
    Compute -->|"Load/Save Settings"| RDS
\`\`\`

## 3. Data Model: User & Settings
A simplified schema design for handling users and their settings in PostgreSQL.

\`\`\`mermaid
erDiagram
    USERS {
        UUID user_id PK
        VARCHAR email
        VARCHAR cognito_sub
        TIMESTAMP created_at
    }
    USER_SETTINGS {
        UUID setting_id PK
        UUID user_id FK
        JSONB preferences "e.g. { theme: 'dark', notifications: true }"
        TIMESTAMP updated_at
    }
    PROJECTS {
        UUID project_id PK
        UUID owner_id FK
        VARCHAR name
        TEXT description
    }

    USERS ||--|| USER_SETTINGS : "has"
    USERS ||--o{ PROJECTS : "owns"
\`\`\`

## 4. Project Phases & Timeline

### Phase 1: Planning & Design
- [ ] Define detailed business requirements.
- [ ] Design DB schema (SchemaSpy / dbdiagram.io).
- [ ] Design API Specification (Swagger/OpenAPI).
- [ ] UI/UX Wireframes (Figma).

### Phase 2: Infrastructure Setup (AWS)
- [ ] Set up AWS Organization & IAM Users.
- [ ] Create VPC with Public/Private subnets.
- [ ] Provision RDS instance (PostgreSQL).
- [ ] Configure Cognito User Pool & App Client.

### Phase 3: Backend Development
- [ ] Initialize repository (Node.js/Python/Go).
- [ ] Implement Authentication Middleware (JWT validation).
- [ ] Create API endpoints for **User Settings**:
    - \`GET /api/settings\`: Retrieve user preferences.
    - \`PUT /api/settings\`: Update user preferences.
- [ ] Implement Project CRUD operations.

### Phase 4: Frontend Development
- [ ] Initialize Web App (React/Vue/Angular).
- [ ] Integrate AWS Amplify SDK or manual Cognito implementation.
- [ ] Build key pages:
    - Login / Sign Up / Forgot Password.
    - Dashboard.
    - Settings Page (connected to valid API).
- [ ] Implement State Management (Redux/Context).

### Phase 5: Testing & QA
- [ ] Unit Testing (Backend & Frontend).
- [ ] Integration Testing (API + DB).
- [ ] User Acceptance Testing (UAT).
- [ ] Security Audit (OWASP Top 10 check).

### Phase 6: Deployment
- [ ] CI/CD Pipeline Setup (GitHub Actions / AWS CodePipeline).
- [ ] Deploy Frontend to S3 + CloudFront.
- [ ] Deploy Backend to Lambda/EC2.
- [ ] DNS Configuration (Route53).

## 5. User Settings specific workflows
**Stroing Settings:**
When a user changes a setting on the frontend (e.g., toggling Dark Mode):
1. Frontend calls \`PUT /settings\` with the new JSON object.
2. Backend validates the session via Cognito.
3. Backend performs an \`UPSERT\` on the \`user_settings\` table in Postgres.

**Accessing Settings:**
On login:
1. Frontend calls \`GET /settings\`.
2. Backend queries \`user_settings\` by \`user_id\`.
3. If no record exists, return default defaults.
4. Frontend applies settings (theme, language, etc).

---
*Template generated by EasyEditor*
`;
    return content;
}
