
export function buildDevOpsPatchingTemplate() {
    const content = `# DevOps: Patch Management Plan

## 1. Overview
This runbook details the process for deploying critical security patches to the production environment.

**Target Systems:**
- AWS EC2 Instances (Linux/Windows)
- Kubernetes Nodes (EKS)
- Database Clusters (RDS)

## 2. Patching Workflow
The following diagram illustrates the end-to-end patching lifecycle.

\`\`\`mermaid
flowchart TD
    Start([Start Patch Cycle]) --> Assess
    
    subgraph Analysis ["Assessment Phase"]
        style Analysis fill:#e6fffa,stroke:#3bb
        Assess[Scan for Vulnerabilities]
        Prioritize[Prioritize Patches]
        Approve[Change Advisory Board Approval]
    end
    
    subgraph Staging ["Testing Phase"]
        style Staging fill:#fff5f5,stroke:#f56565
        DeployStage[Deploy to Staging]
        TestStage[Run Regression Tests]
        Verify{Tests Passed?}
    end
    
    subgraph Production ["Deployment Phase"]
        style Production fill:#ebf8ff,stroke:#4299e1
        Backup[Create Snapshots/Backups]
        RollingUpdate[Rolling Update / Patch]
        HealthCheck[Health Check]
        Rollback{Issues Found?}
    end

    Assess --> Prioritize
    Prioritize --> Approve
    Approve --> DeployStage
    DeployStage --> TestStage
    TestStage --> Verify
    
    Verify -- No --> Fix["Investigate & Fix"]
    Fix --> DeployStage
    
    Verify -- Yes --> Backup
    Backup --> RollingUpdate
    RollingUpdate --> HealthCheck
    HealthCheck --> Rollback
    
    Rollback -- Yes --> Restore[Restore from Backup]
    Rollback -- No --> Notify[Notify Stakeholders]
    Restore --> Notify
    Notify --> End([End Cycle])
\`\`\`

## 3. Patch Status Board
Status of the current patching cycle.

\`\`\`mermaid
kanban
  Todo
    [Run CVE Scans on Prod]
    [Check vendor advisories]
    [Schedule maintenance window]
  In Progress
    [Apply kernel updates KB4567]
    [Update Docker runtime]
  Testing
    [Verify API connectivity]
    [Validation scan]
  Blocked
    [Legacy App Compatibility]
    [Vendor Patch Delayed]
  Done
    [Update dependency lockfiles]
    [Update runbook for v2.1]
\`\`\`

## 4. Execution Checklist

### pre-flight
- [ ] **Notification:** Inform stakeholders 24h in advance.
- [ ] **Backup:** Verify automated backups are successful.
- [ ] **Monitoring:** Silences non-critical alerts for the maintenance window.

### deployment
- [ ] **Stop Services:** Drain connections from target nodes.
- [ ] **Apply Patch:**
    \`\`\`bash
    # Example command
    sudo apt-get update && sudo apt-get dist-upgrade -y
    \`\`\`
- [ ] **Reboot:** Restart services/nodes if required.

### post-patch verification
- [ ] **Sanity Check:** verify \`systemctl status application\`.
- [ ] **Logs:** Check \`/var/log/syslog\` for errors.
- [ ] **Performance:** Monitor CPU/Memory usage for anomalies.

## 5. Rollback Plan
If critical issues arise within **15 minutes** of deployment:
1. Revert VM snapshots / switch traffic to Blue environment.
2. Restore database from pre-patch point-in-time recovery.
3. Notify Incident Response team.

---
*Template generated by EasyEditor*
`;
    return content;
}
